// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnujvbpwlxczzvhzrukp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudWp2YnB3bHhjenp2aHpydWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Mjk1NTQsImV4cCI6MjA3MTUwNTU1NH0.bruVzLv7OQUSMZirT3JcJ7t69ca5_TdNAvsEOrIj8WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});